language: ruby


# This intended to fix bundler bug in Ruby 1.9.3 (see https://github.com/travis-ci/travis-ci/issues/5239)
before_install:
  - gem install bundler


rvm:
- 2.6.2
- 2.4.5
- jruby-head

script: "bundle exec rspec spec"
